opt_in_rules:
    - indentation_width
    - closure_spacing
    - sorted_imports
    - vertical_parameter_alignment_on_call
    - vertical_parameter_alignment
    
disabled_rules:
    - trailing_whitespace
    
included:
  - Sources
excluded:
  - Tests

line_length: 150
